### PR TITLE
Add formatting to the CI

### PR DESCRIPTION
**Pull request by marioortizmanero**
I often find small formatting inconsistencies in the codebase, which make the code somewhat harder to read for me. I think this should be enforced with the CI, as many more projects do.

It seems you have configured the formatter for the nightly compiler, so I've added it to the nightly step.

### CODE REVIEW

**Comment by marioortizmanero** [comment]
So that this passes the CI checks now, I have to run a `cargo fmt`. This will unfortunately add lots of changes to this PR and make it harder to review, but you can reproduce it yourself and see how I didn't touch anything else.

**Comment by marioortizmanero** [comment]
Uhm, I'm actually not sure why the CI doesn't run for pull requests. Have you configured it that way yourself on GitHub?

**Comment by rodrimati1992** [comment]
> Uhm, I'm actually not sure why the CI doesn't run for pull requests. Have you configured it that way yourself on GitHub?

Yes, there's a time limit for free CI which would only allow 24 runs a month with my current configuration.

Aside from that, your [other pull request](https://github.com/rodrimati1992/abi_stable_crates/pull/55) didn't need a CI run because it modified code that wasn't even tested (working on that right now).

I'll format all of the crates in the repo (and do whatever's necessary to enforce formatting in CI) as part of the PR where I add more tests.

**Comment by marioortizmanero** [comment]
It would also be really nice to have `clippy` integrated into the CI. There are some aspects about `abi_stable` that it's not very happy about, and that would make the crate much cleaner.

**Pull request closed without merging**
